In [1]:
import pandas as pd

In [34]:
import pandas as pd

data = {
    "Name": ["Arun", "Priya", "Karthik", "Meena", "Rahul", "Priya"],
    "Age": [25, 24, 27, None, 23, 24],
    "Department": ["IT", "HR", "IT", "Finance", "HR", "HR"],
    "Salary": [50000, 45000, 65000, 55000, None, 45000],
    "City": ["Chennai", "Bangalore", "Chennai",
             "Mumbai", "Bangalore", "Bangalore"]
}

df = pd.DataFrame(data)
print(df)

      Name   Age Department   Salary       City
0     Arun  25.0         IT  50000.0    Chennai
1    Priya  24.0         HR  45000.0  Bangalore
2  Karthik  27.0         IT  65000.0    Chennai
3    Meena   NaN    Finance  55000.0     Mumbai
4    Rahul  23.0         HR      NaN  Bangalore
5    Priya  24.0         HR  45000.0  Bangalore

In [35]:
df['Age'].fillna(df['Age'].mean(), inplace=True)
df

C:\Users\ASM9017\AppData\Local\Temp\ipykernel_47384\1943981980.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Age'].fillna(df['Age'].mean(), inplace=True)

      Name   Age Department   Salary       City
0     Arun  25.0         IT  50000.0    Chennai
1    Priya  24.0         HR  45000.0  Bangalore
2  Karthik  27.0         IT  65000.0    Chennai
3    Meena  24.6    Finance  55000.0     Mumbai
4    Rahul  23.0         HR      NaN  Bangalore
5    Priya  24.0         HR  45000.0  Bangalore

In [3]:
df["age"] = df["Age"] +10

In [9]:
df1 =df.dropna()

In [10]:
df.loc[df['Age'] > 25, ['Name']]

      Name
2  Karthik

In [ ]:
df.groupby("Department")["Salary"].mean()

Department
Finance    55000.0
HR         30000.0
IT         57500.0
Name: Salary, dtype: float64

In [ ]:
d1=df.groupby(["Department","City"])["Salary"].mean()
d1.sort_index()
d1

Department  City
Finance     Mumbai       55000.0
HR          Bangalore    30000.0
IT          Chennai      57500.0
Name: Salary, dtype: float64

In [23]:
employees = pd.DataFrame({
    "Employee_ID": [1, 2, 3],
    "Name": ["Arun", "Priya", "Karthik"],
    "Department_ID": [10, 20, 10]
})
departments = pd.DataFrame({
    "Department_ID": [10, 20, 30],
    "Department": ["IT", "HR", "Finance"]
})

m1 = pd.merge(employees, departments, on="Department_ID", how="inner")
m1

   Employee_ID     Name  Department_ID Department
0            1     Arun             10         IT
1            2    Priya             20         HR
2            3  Karthik             10         IT

In [26]:
m1.groupby("Department")["Department_ID"].count()

Department
HR    1
IT    2
Name: Department_ID, dtype: int64

In [28]:
wide = pd.DataFrame({
    "Name": ["Arun", "Priya"],
    "Maths": [90, 85],
    "Science": [88, 92]
})

long = wide.melt(
    id_vars=["Name"],
    var_name="Subject",
    value_name="Marks"
)

long

    Name  Subject  Marks
0   Arun    Maths     90
1  Priya    Maths     85
2   Arun  Science     88
3  Priya  Science     92

In [ ]:
import pandas as pd

# 1. Load data
df = pd.read_csv("employees.csv")

# 2. Inspect
print(df.head())
print(df.shape)
print(df.info())
print(df.isna().sum())

# 3. Clean column names
df.columns = df.columns.str.strip().str.lower()

# 4. Remove duplicate rows
df = df.drop_duplicates()

# 5. Convert data types
df["salary"] = pd.to_numeric(df["salary"], errors="coerce")
df["age"] = pd.to_numeric(df["age"], errors="coerce")

# 6. Fill missing numeric values
for col in ["salary", "age"]:
    df[col] = df[col].fillna(df[col].median())

# 7. Analyze data
summary = df.groupby("department").agg(
    average_salary=("salary", "mean"),
    employee_count=("salary", "size")
)

# 8. Filter
high_salary = df.loc[df["salary"] > 50000]

# 9. Export results
summary.to_csv("department_summary.csv")

print(summary)
print(high_salary.head())